import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import { VitePWA } from "vite-plugin-pwa";

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    react(),
    VitePWA({
      registerType: "autoUpdate",
      // Gemini COMMENT: 'injectManifest' is the correct strategy for a custom service worker.
      strategies: "injectManifest",
      // Gemini COMMENT: This MUST point to the source file that will be built.
      srcDir: "src",
      filename: "firebase-messaging-sw.js",
      // Gemini COMMENT: The manifest is configured here to be generated by the plugin.
      manifest: {
        name: "Last Checked In",
        short_name: "LCI",
        description:
          "A Personal Relationship Manager to nurture your connections.",
        theme_color: "#1a1a1a",
        icons: [
          {
            src: "/LogoV1.png", // This path is relative to the `public` directory.
            sizes: "192x192 512x512",
            type: "image/png",
          },
        ],
      },
      // Gemini COMMENT:it is the REQUIRED configuration to enable the PWA plugin during development
      // Without this, the dev server will not generate the manifest or serve the service worker.
      devOptions: {
        enabled: true,
        // Gemini COMMENT: CRITICAL FIX - THIS IS THE ENTIRE FIX.
        // This tells the browser to load our service worker as an ES Module.
        // Our firebase-messaging-sw.js uses `import` statements, which makes this mandatory.
        // The 'TypeError' about an invalid WorkerType was caused by this line being absent.
        type: "module",
      },
    }),
  ],
});
